---
title: "EDA"
output: html_notebook
---

## Libraries
```{r}
library(tidyverse)
```

## Loading Data and Summaries

We initially thought of considering the entire dataset (both train and test)

But that only slowed down the visualizing.

```{r}
train_df <- read.csv("../credit_card_default_train.csv")
train_df$NEXT_MONTH_DEFAULT <- as.factor(train_df$NEXT_MONTH_DEFAULT)
test_df <- read.csv("../credit_card_default_test.csv")
df <- train_df
print(nrow(df))
print(colnames(df))
print(str(df))
print(summary(df))

```

## Visualizing Numerical Data

```{r}
ggplot(data=gather(train_df,key,value,c("DUE_AMT_JULY","DUE_AMT_AUG",
                                        "DUE_AMT_SEP","DUE_AMT_OCT",
                                        "DUE_AMT_NOV","DUE_AMT_DEC")),
       aes(x = key,y = value))+
  geom_violin()
```

```{r}
ggplot(data=gather(train_df,key,value,c("PAID_AMT_JULY","PAID_AMT_AUG",
                                      "PAID_AMT_SEP","PAID_AMT_OCT",
                                      "PAID_AMT_NOV","PAID_AMT_DEC")),
       aes(x = key,y = value))+
  geom_violin()
```

## Patterns of response variable



```{r}
ggplot(data=gather(train_df,key,value,c("PAY_JULY","PAY_AUG",
                                        "PAY_SEP","PAY_OCT",
                                        "PAY_NOV","PAY_DEC")) %>%
         mutate(key = as.factor(key), value=as.factor(value)),
       aes(x=key,y=value,group=Client_ID))+
  geom_line(aes(color=NEXT_MONTH_DEFAULT),size=0.1)+
  geom_point(aes(color=NEXT_MONTH_DEFAULT),size=0.1)+
  scale_y_discrete(labels=as.character(seq(-2,9)))
```

