---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(randomForest)
library(randomForestExplainer)
library(MLmetrics)
```
## Loading Data
```{r}
train_df <- read.csv("../credit_card_default_train.csv")
test_df <- read.csv("../credit_card_default_test.csv")
submission <- test_df[,"Client_ID"]
submission$NEXT_MONTH_DEFAULT <- 0
```
## Preprocessing
```{r}
train_df$NEXT_MONTH_DEFAULT <- as.factor(as.numeric(train_df$NEXT_MONTH_DEFAULT))
factor_pay <- function(x){factor(x,levels=seq(-2,9))}
# train_df <- train_df %>% mutate_at(c("PAY_JULY","PAY_AUG","PAY_SEP",
#                                      "PAY_OCT","PAY_NOV","PAY_DEC"),factor_pay)
# normalize <- function(x){(x - mean(x)/sd(x))}
train_df <- train_df %>% mutate_at(c("DUE_AMT_JULY","DUE_AMT_AUG",
                                     "DUE_AMT_SEP","DUE_AMT_OCT",
                                     "DUE_AMT_NOV","DUE_AMT_DEC",
                                     "PAID_AMT_JULY","PAID_AMT_AUG",
                                     "PAID_AMT_SEP","PAID_AMT_OCT",
                                     "PAID_AMT_NOV","PAID_AMT_DEC"),scale)
blv <- train_df%>% 
  mutate(Balance_Limit_V1=trimws(Balance_Limit_V1)) %>% 
  subset(select=Balance_Limit_V1)
train_df$Balance_Limit_V1 <- factor(as.factor(blv$Balance_Limit_V1),
                          levels=c("100K","200K","300K","400K","500K","1M","1.5M","2.5M"))
```

```{r,echo=FALSE}
# test_df <- test_df %>% mutate_at(c("PAY_JULY","PAY_AUG","PAY_SEP",
#                                      "PAY_OCT","PAY_NOV","PAY_DEC"),factor_pay)
test_df <- test_df %>% mutate_at(c("DUE_AMT_JULY","DUE_AMT_AUG",
                                   "DUE_AMT_SEP","DUE_AMT_OCT",
                                   "DUE_AMT_NOV","DUE_AMT_DEC",
                                   "PAID_AMT_JULY","PAID_AMT_AUG",
                                   "PAID_AMT_SEP","PAID_AMT_OCT",
                                   "PAID_AMT_NOV","PAID_AMT_DEC"),scale)
blv <- test_df%>% 
  mutate(Balance_Limit_V1=trimws(Balance_Limit_V1)) %>% 
  subset(select=Balance_Limit_V1)
test_df$Balance_Limit_V1 <- factor(as.factor(blv$Balance_Limit_V1),
                          levels=c("100K","200K","300K","400K","500K","1M","1.5M","2.5M"))
```
## Feature Engineering
```{r}
train_df <- train_df %>% mutate(
  Balance_Limit_V1 = case_when(
    Balance_Limit_V1 == "100K" ~ 100,
    Balance_Limit_V1 == "200K" ~ 200,
    Balance_Limit_V1 == "300K" ~ 300,
    Balance_Limit_V1 == "400K" ~ 400,
    Balance_Limit_V1 == "500K" ~ 500,
    Balance_Limit_V1 == "1M" ~ 1000,
    Balance_Limit_V1 == "1.5M" ~ 1500,
    Balance_Limit_V1 == "2M" ~ 2000,
    Balance_Limit_V1 == "2.5M" ~ 2500
  )) %>% 
  subset(select=-c(Gender,MARITAL_STATUS)) %>%
  mutate(EDUCATION_STATUS = as.numeric(EDUCATION_STATUS),
         AGE = as.numeric(AGE))%>%
  subset(select=-c(DUE_AMT_JULY,DUE_AMT_AUG,
                                     DUE_AMT_SEP,DUE_AMT_OCT,
                                     DUE_AMT_NOV,DUE_AMT_DEC,
                                     PAID_AMT_JULY,PAID_AMT_AUG,
                                     PAID_AMT_SEP,PAID_AMT_OCT,
                                     PAID_AMT_NOV,PAID_AMT_DEC))
  # mutate(
  #   Due_Credit_Lim_JULY=(DUE_AMT_JULY/Balance_Limit_V1) * 100,
  #   Due_Credit_Lim_AUG=(DUE_AMT_AUG/Balance_Limit_V1) * 100,
  #   Due_Credit_Lim_SEP=(DUE_AMT_SEP/Balance_Limit_V1) * 100,
  #   Due_Credit_Lim_OCT=(DUE_AMT_OCT/Balance_Limit_V1) * 100,
  #   Due_Credit_Lim_NOV=(DUE_AMT_NOV/Balance_Limit_V1) * 100,
  #   Due_Credit_Lim_DEC=(DUE_AMT_DEC/Balance_Limit_V1) * 100
  # )
```
## Splitting
```{r}
train_split <- train_df %>% sample_frac(0.65)
validation_split <- train_df %>% anti_join(train_split,by="Client_ID")
test_split <- validation_split %>% sample_frac(0.5)
validation_split <- validation_split %>% anti_join(test_split,by="Client_ID")
str(train_split)
```

## Model fitting
```{r}
set.seed(2017)
forest <- randomForest(NEXT_MONTH_DEFAULT ~ ., 
                       data = subset(train_split,select=-Client_ID), 
                       localImp = TRUE,
                       classwt=c(0.2,0.8))
```
```{r}
forest
```
## Confusion Matrix
```{r}
predictions<-predict(forest,subset(test_split,select=-c(Client_ID,NEXT_MONTH_DEFAULT)))
cm <- CrossTable(predictions,test_split$NEXT_MONTH_DEFAULT)
F1_Score(predictions,test_split$NEXT_MONTH_DEFAULT)
cm
```
## Variable Importances
```{r}
importance_frame <- measure_importance(forest)
save(importance_frame, file = "importance_frame.rda")
load("importance_frame.rda")
importance_frame
```
```{r}
importance_frame[order(importance_frame$accuracy_decrease),]
```