---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(MLmetrics)
library(caret)
library(xgboost)
```

## Loading Data
```{r}
#loading the glm output for test_df
glm_out_train <- read.csv("ensemble_data/glm_ensemble_train.csv")
rf_out_train <- read.csv("ensemble_data/rf_ensemble_train.csv")
svm_out_train <- read.csv("ensemble_data/svm_ensemble_train.csv")

train_df <- read.csv("../credit_card_default_train.csv")
train_df <- train_df %>% subset(select=c(Client_ID,NEXT_MONTH_DEFAULT))
train_df <- train_df %>%
  left_join(glm_out_train,by=c("Client_ID")) %>% 
  left_join(rf_out_train,by=c("Client_ID")) %>% 
  left_join(svm_out_train,by=c("Client_ID"))

glm_out_test <- read.csv("ensemble_data/glm_ensemble_test.csv")
rf_out_test <- read.csv("ensemble_data/rf_ensemble_test.csv")
svm_out_test <- read.csv("ensemble_data/svm_ensemble_test.csv")

test_df <- read.csv("../credit_card_default_test.csv")
test_df <- test_df %>% subset(select=Client_ID)
test_df <- test_df %>% 
  left_join(glm_out_test,by=c("Client_ID")) %>% 
  left_join(rf_out_test,by=c("Client_ID")) %>% 
  left_join(svm_out_test,by=c("Client_ID"))

```
```{r}
train_df[rowSums(is.na(train_df))>0,]
test_df[rowSums(is.na(test_df))>0,]
```
## Splitting

```{r}
train_index <- createDataPartition(train_df$NEXT_MONTH_DEFAULT, p = 0.7, list = FALSE)
train_split <- train_df[ train_index,]
validation_split  <- train_df[-train_index,]
```

## Model fitting

```{r}
bstDense <- xgboost(data = as.matrix(subset(train_split,select=-c(Client_ID,NEXT_MONTH_DEFAULT))), 
                    label = train_split$NEXT_MONTH_DEFAULT, 
                    max.depth = 5, eta = 0.41, nthread = -1, nrounds = 5, 
                    objective = "binary:logistic",verbose = 2)
```

## Prediction
```{r}
predictions_ <- predict(bstDense, as.matrix(subset(validation_split,select=-c(Client_ID,NEXT_MONTH_DEFAULT))))
predictions <- ifelse(predictions_ >= 0.5,1,0)
cm <- CrossTable(predictions,validation_split$NEXT_MONTH_DEFAULT)
F1_Score(predictions,validation_split$NEXT_MONTH_DEFAULT)
```

```{r}
plotdf <- data.frame(
  one = predictions_,
  zero = 1-predictions_,
  actual_value = as.factor(validation_split$NEXT_MONTH_DEFAULT)
)
ggplot(data=plotdf,aes(x=zero,y=one))+
  geom_point(aes(color=actual_value))
```

```{r}
importance_matrix <- xgb.importance(model = bstDense)
print(importance_matrix)
xgb.plot.importance(importance_matrix = importance_matrix)
```

```{r}
test_predictions <- predict(bstDense,as.matrix(subset(test_df,select=-c(Client_ID))))
test_predictions <- ifelse(test_predictions >= 0.5,1,0)
```

```{r}
submission <- subset(test_df,select=Client_ID)
submission$NEXT_MONTH_DEFAULT <- test_predictions
write.csv(submission,"output/ensemble_1105_PM.csv",row.names=F)
```