---
title: "R Notebook"
output: html_notebook
---
```{r}
library(tidyverse)
library(ggridges)
```
# Visualizing new features

```{r}
train_df <- read.csv("../credit_card_default_train.csv")
train_df$NEXT_MONTH_DEFAULT <- as.factor(train_df$NEXT_MONTH_DEFAULT)
train_df$PAY_JULY <- factor(train_df$PAY_JULY,levels=as.character(seq(-2,9)))
train_df$PAY_AUG <- factor(train_df$PAY_AUG,levels=as.character(seq(-2,9)))
train_df$PAY_SEP <- factor(train_df$PAY_SEP,levels=as.character(seq(-2,9)))
train_df$PAY_OCT <- factor(train_df$PAY_OCT,levels=as.character(seq(-2,9)))
train_df$PAY_NOV <- factor(train_df$PAY_NOV,levels=as.character(seq(-2,9)))
train_df$PAY_DEC <- factor(train_df$PAY_DEC,levels=as.character(seq(-2,9)))
test_df <- read.csv("../credit_card_default_test.csv")
```

Cosnidering the pay delay and paid amounts for the six months

```{r}
ggplot(data=train_df%>%
         gather(pay_key,pay_value,c("PAY_JULY","PAY_AUG",
                                        "PAY_SEP","PAY_OCT",
                                        "PAY_NOV","PAY_DEC")) %>%
         gather(paid_key,paid_value,c("PAID_AMT_JULY","PAID_AMT_AUG",
                                      "PAID_AMT_SEP","PAID_AMT_OCT",
                                      "PAID_AMT_NOV","PAID_AMT_DEC")) %>%
         mutate(pay_key = factor(pay_key,levels=c("PAY_JULY","PAY_AUG",
                                        "PAY_SEP","PAY_OCT",
                                        "PAY_NOV","PAY_DEC"))),
       aes(y=paid_value,x=pay_value,fill=NEXT_MONTH_DEFAULT))+
  # geom_line(aes(color=NEXT_MONTH_DEFAULT))+
  geom_bar(position="dodge", stat="identity")+
  facet_grid(pay_key ~ .) + theme_minimal()
```


Considering the balance of months

```{r}
train_df$balance_july <- train_df$DUE_AMT_JULY - train_df$PAID_AMT_JULY
train_df$balance_aug <- train_df$DUE_AMT_AUG - train_df$PAID_AMT_AUG
train_df$balance_sep <- train_df$DUE_AMT_SEP - train_df$PAID_AMT_SEP
train_df$balance_oct <- train_df$DUE_AMT_OCT - train_df$PAID_AMT_OCT
train_df$balance_nov <- train_df$DUE_AMT_NOV - train_df$PAID_AMT_NOV
train_df$balance_dec <- train_df$DUE_AMT_DEC - train_df$PAID_AMT_DEC

ggplot(data=gather(train_df,key,value,c("balance_july","balance_aug",
                                        "balance_sep","balance_oct",
                                        "balance_nov","balance_dec")) %>%
         mutate(key = factor(key,levels =c("balance_july","balance_aug",
                                        "balance_sep","balance_oct",
                                        "balance_nov","balance_dec"))),
       aes(x = key,y = value))+
  geom_boxplot(aes(fill=NEXT_MONTH_DEFAULT))+theme_minimal()
```

Balance as a percentage of credit limit

```{r}
train_df <- train_df %>% mutate(
  Balance_Credit_Limit_Numeric = case_when(
    Balance_Limit_V1 == "100K" ~ 100000,
    Balance_Limit_V1 == "200K" ~ 200000,
    Balance_Limit_V1 == "300K" ~ 300000,
    Balance_Limit_V1 == "400K" ~ 400000,
    Balance_Limit_V1 == "500K" ~ 500000,
    Balance_Limit_V1 == "1M" ~ 1000000,
    Balance_Limit_V1 == "1.5M" ~ 1500000,
    Balance_Limit_V1 == "2M" ~ 2000000,
    Balance_Limit_V1 == "2.5M" ~ 2500000
  )
) %>%
  mutate(
    balance_Credit_Lim_JULY=(balance_july/Balance_Credit_Limit_Numeric) * 100,
    balance_Credit_Lim_AUG=(balance_aug/Balance_Credit_Limit_Numeric) * 100,
    balance_Credit_Lim_SEP=(balance_sep/Balance_Credit_Limit_Numeric) * 100,
    balance_Credit_Lim_OCT=(balance_oct/Balance_Credit_Limit_Numeric) * 100,
    balance_Credit_Lim_NOV=(balance_nov/Balance_Credit_Limit_Numeric) * 100,
    balance_Credit_Lim_DEC=(balance_dec/Balance_Credit_Limit_Numeric) * 100
  ) %>%
  na.omit()
```

Plotting

```{r}
ggplot(data=gather(train_df,key,value,c("balance_Credit_Lim_JULY","balance_Credit_Lim_AUG",
                                        "balance_Credit_Lim_SEP","balance_Credit_Lim_OCT",
                                        "balance_Credit_Lim_NOV","balance_Credit_Lim_DEC")) %>%
         mutate(key = factor(key,levels=c("balance_Credit_Lim_JULY","balance_Credit_Lim_AUG",
                                        "balance_Credit_Lim_SEP","balance_Credit_Lim_OCT",
                                        "balance_Credit_Lim_NOV","balance_Credit_Lim_DEC"))),
       aes(x=key,y=value))+
  geom_boxplot(aes(fill=NEXT_MONTH_DEFAULT))+
  coord_cartesian(ylim=c(0,200))+
  scale_x_discrete(labels=c("JULY","AUG","SEP","OCT","NOV","DEC"))
```